# Generated by Django 5.0.1 on 2024-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_list', '0002_task_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Отчет'),
        ),
    ]
